# Generated by Django 6.0.4 on 2026-08-12 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_experience_resume_alter_project_resume_and_more'),
        ('candidate', '0001_initial'),
        ('recruiter', '0002_alter_recruitment_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_job', to='recruiter.recruitment'),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_resume', to='authentication.resume'),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_user', to='authentication.userprofile'),
        ),
    ]
