# Generated by Django 6.0.4 on 2026-08-12 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_experience_resume_alter_project_resume_and_more'),
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting_by_recruiter', to='authentication.recruiterprofile'),
        ),
    ]
