# Generated by Django 6.0.4 on 2026-08-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_alter_recruitment_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='organisation_name',
            field=models.CharField(max_length=255),
        ),
    ]
