# Generated by Django 6.0.4 on 2026-08-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0003_alter_recruitment_organisation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
